# Generated by Django 3.2.13 on 2022-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='position',
            field=models.CharField(max_length=64, verbose_name='채용포지션'),
        ),
    ]
